#!/usr/bin/with-contenv bash

# install CMS if optioned
if [ "${INSTALL_CMS}" = "true" ]; then
   cp -rf /home/grav/* ${WEB_ROOT};
fi

${WEB_ROOT}bin/gpm update
${WEB_ROOT}bin/gpm selfupgrade
${WEB_ROOT}bin/grav install
${WEB_ROOT}bin/grav composer
${WEB_ROOT}bin/grav cache

# if production mode
if [ "${BUILD_ENV}" = "prod" ]; then
   ${WEB_ROOT}bin/grav clean
fi

# Make sure web root is owned by web user and group
chown -R "$WEB_USER":"$WEB_GROUP" "$WEB_ROOT"
